In [1]:
from scipy import interpolate as ip

In [12]:
X = np.linspace(0.2, 1, 5)
Y = np.array(','.join(("0.9798652 0.9177710 0.808038 0.6386093 0.3843735").split(' ')).split(','), dtype='float')
X, Y

(array([0.2, 0.4, 0.6, 0.8, 1. ]),
 array([0.9798652, 0.917771 , 0.808038 , 0.6386093, 0.3843735]))

In [14]:
poly = ip.lagrange(X, Y)

In [33]:
poly.deriv().coef

array([-1.35984375,  1.28620938, -1.54001562,  0.07228279])

In [37]:
po = sum(sy.S("{:6.6f}".format(v))*x**i for i, v in enumerate(poly.deriv().deriv().coef[::-1]))
eq_latex = sy.printing.latex(po)

In [38]:
tex(eq_latex)

In [17]:
poly.deriv()(0.4)

-0.4249599583332933

In [18]:
poly.deriv().deriv()(0.4)

-1.1637731249998613