In [1]:
from sympy import parsing
from sympy.parsing import latex

In [73]:
A, B, C, D, E, fx, x_0, h, v = sy.symbols('A B C D E f(x_0) x_0 h, v')

In [111]:
F = sy.Function('f')

In [74]:
fx = x_0 - v * h

In [93]:
X = [
    [1, 1, 1, 1, 1],
    [-1, 0, 1, 2, 3],
    [0.5, 0, 0.5, 2, 4.5],
    (1/6) * np.array([-1, 0, 1, 8, 27]),
    (1/24) * np.array([1, 0, 1, 16, 81])
]
Y = np.array([0, 1, 0, 0, 0]).reshape(5, 1)
X, Y

([[1, 1, 1, 1, 1],
  [-1, 0, 1, 2, 3],
  [0.5, 0, 0.5, 2, 4.5],
  array([-0.16666667,  0.        ,  0.16666667,  1.33333333,  4.5       ]),
  array([0.04166667, 0.        , 0.04166667, 0.66666667, 3.375     ])],
 array([[0],
        [1],
        [0],
        [0],
        [0]]))

In [102]:
ans = (np.round(np.array(sy.linsolve((sy.Matrix(X), sy.Matrix(Y))).args[0], dtype='float'), 8))
ans = ans / h

In [112]:
eq = sy.sympify(0)
hvals = [-1, 0, 1, 2, 3]
for i in range(5):
    display(ans[i], F(fx.subs(v, hvals[i])))
    eq += ans[i] * F(fx.subs(v, hvals[i]))

-0.25/h

f(h + x_0)

-0.83333333/h

f(x_0)

1.5/h

f(-h + x_0)

-0.5/h

f(-2*h + x_0)

0.08333333/h

f(-3*h + x_0)

In [113]:
eq

-0.83333333*f(x_0)/h + 0.08333333*f(-3*h + x_0)/h - 0.5*f(-2*h + x_0)/h + 1.5*f(-h + x_0)/h - 0.25*f(h + x_0)/h

In [117]:
from scipy import interpolate as ip

In [155]:
X = np.array([','.join("0.2 0.4 0.6 0.8 1.0".split(' ')).split(',')][0],  dtype='float32')
Y = np.array([','.join("0.9798652 0.9177710 0.8080348 0.6386093 0.3843735".split(' ')).split(',')][0], dtype='float32')
data = dict(zip(X, Y))
print(data)
fm = lambda k: data[np.float32(k)]

{0.2: 0.9798652, 0.4: 0.917771, 0.6: 0.8080348, 0.8: 0.6386093, 1.0: 0.3843735}


In [158]:
eq.subs(h, 0.2).subs(x_0, 0.4).replace(F, fm)

KeyError: -0.2

In [157]:
eq.subs(h, 0.2).subs(x_0, 0.8).replace(F, fm)

1.03277163632182