In [76]:
from scipy import interpolate as ip

In [18]:
h = sy.symbols('h')

In [10]:
hvals = [-1, 0, 1, 2, 3]
ans = np.array([-0.25      , -0.83333333,  1.5       , -0.5       ,  0.08333333])

In [90]:
ans * 12

array([-3.        , -9.99999996, 18.        , -6.        ,  0.99999996])

In [115]:
X = np.array([','.join("0.2 0.4 0.6 0.8 1.0".split(' ')).split(',')][0],  dtype='float32')
Y = np.array([','.join("0.9798652 0.9177710 0.8080348 0.6386093 0.3843735".split(' ')).split(',')][0], dtype='float32')
X, Y

(array([0.2, 0.4, 0.6, 0.8, 1. ], dtype=float32),
 array([0.9798652, 0.917771 , 0.8080348, 0.6386093, 0.3843735],
       dtype=float32))

In [126]:
data = dict(zip(X, Y))
fx = lambda k: data[k] if k in data else ip.lagrange(X, Y)(k)
F = sy.Function ('f')
x0 = sy.symbols('x_0')

In [127]:
dF = ((12) * (ans[0] * F(x0 - h) + ans[1] * F(x0) + 1.5 * F(x0 + h) - 0.5 * F(x0 + 2*h) + ans[4] * F(x0+3*h))) / (12 * 0.2)

In [128]:
dF 

-4.16666665*f(x_0) - 1.25*f(-h + x_0) + 7.5*f(h + x_0) - 2.5*f(2*h + x_0) + 0.41666665*f(3*h + x_0)

In [132]:
tex(dF.subs([(h, 0.2), (x0, 0.4)]))

In [133]:
tex(dF.subs([(h, 0.2), (x0, 0.8)]))