In [31]:
import functools

In [2]:
def getNDDCoeffs(X, Y):
    """ Creates NDD pYramid and eXtracts coeffs """
    n = np.shape(Y)[0]
    pYramid = np.zeros([n, n]) # Create a square matriX to hold pYramid
    pYramid[::,0] = Y # first column is Y
    for j in range(1,n):
        for i in range(n-j):
            # create pYramid bY updating other columns
            pYramid[i][j] = (pYramid[i+1][j-1] - pYramid[i][j-1]) / (X[i+j] - X[i])
    return pYramid[0] # return first row

In [19]:
X = np.linspace(0.1, 0.4, 4)

In [20]:
Y = [-0.62049958, -0.28398668, 0.00660095, 0.24842440]

In [27]:
deg1 = getNDDCoeffs(X[1:3], Y[1:3])
deg2 = getNDDCoeffs(X[1:4], Y[1:4])
deg3 = getNDDCoeffs(X, Y)

In [28]:
display((deg1, X[1:3], Y[1:3]), (deg2, X[1:4], Y[1:4]), deg3)

(array([-0.28398668,  2.9058763 ]),
 array([0.2, 0.3]),
 [-0.28398668, 0.00660095])

(array([-0.28398668,  2.9058763 , -2.438209  ]),
 array([0.2, 0.3, 0.4]),
 [-0.28398668, 0.00660095, 0.2484244])

array([-0.62049958,  3.365129  , -2.2962635 , -0.47315167])

In [36]:
eqs = []
for d in [deg1, deg2, deg3]:
    eq = sy.sympify(0)
    for i, k in enumerate(d):
        xterms = functools.reduce(lambda x, y: x * y, [(x - j) for j in X[:i]]) if i != 0 else 1
        eq += k * xterms
    eqs.append(eq)

In [41]:
for i in eqs:
    display(i.subs(x, 0.25))

0.151894765000000

0.133608197500000

-0.132774774375000