In [1]:
X = 1
FX = lambda k: np.log(k)
h = 0.4

In [2]:
def richardson( f, x, n, h ):
    """Richardson's Extrapolation to approximate  f'(x) at a particular x.

    USAGE:
	d = richardson( f, x, n, h )

    INPUT:
	f	- function to find derivative of
	x	- value of x to find derivative at
	n	- number of levels of extrapolation
	h	- initial stepsize

    OUTPUT:
        np float array -  two-dimensional array of extrapolation values.
                             The [n,n] value of this array should be the
                             most accurate estimate of f'(x).

    NOTES:                             
        Based on an algorithm in "Numerical Mathematics and Computing"
        4th Edition, by Cheney and Kincaid, Brooks-Cole, 1999.

    AUTHOR:
        Jonathan R. Senning <jonathan.senning@gordon.edu>
        Gordon College
        February 9, 1999
        Converted ty Python August 2008
    """

    # d[n,n] will contain the most accurate approximation to f'(x).

    d = np.array( [[0] * (n + 1)] * (n + 1), float )
    print(d)

    for i in range( n + 1 ):
        d[i,0] = 0.5 * ( f( x + h ) - f( x - h ) ) / h
        print(d)

        powerOf4 = 1  # values of 4^j
        for j in range( 1, i + 1 ):
            powerOf4 = 4 * powerOf4
            d[i,j] = d[i,j-1] + ( d[i,j-1] - d[i-1,j-1] ) / ( powerOf4 - 1 )
            print(d)

        h = 0.5 * h

    return d

In [3]:
# cant use this, this is center diff. not forward diff
richardson(FX, X, 3, h)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1.05912233 0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]
[[1.05912233 0.         0.         0.        ]
 [1.01366277 0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]
[[1.05912233 0.         0.         0.        ]
 [1.01366277 0.99850959 0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]]
[[1.05912233 0.         0.         0.        ]
 [1.01366277 0.99850959 0.         0.        ]
 [1.00335348 0.         0.         0.        ]
 [0.         0.         0.         0.        ]]
[[1.05912233 0.         0.         0.        ]
 [1.01366277 0.99850959 0.         0.        ]
 [1.00335348 0.99991705 0.         0.        ]
 [0.         0.         0.         0.     

array([[1.05912233, 0.        , 0.        , 0.        ],
       [1.01366277, 0.99850959, 0.        , 0.        ],
       [1.00335348, 0.99991705, 1.00001088, 0.        ],
       [1.00083459, 0.99999495, 1.00000015, 0.99999998]])

In [4]:
X, h

(1, 0.4)

In [5]:
n = 5

In [6]:
fwd = lambda a, b, fa, fb: (fb -fa) / (b - a)

In [7]:
d = []

In [8]:
step = h
di = []
for i in range(n + 1):
    di.append(fwd(X, X+step, FX(X), FX(X+step)))
    step /= 2
d.append(di)

In [9]:
di2 = []
for i in range(n):
    di2.append(2 * d[0][i+1] - d[0][i])

In [10]:
d.append(di2)

In [11]:
d

[[0.8411805915530324,
  0.9116077839697732,
  0.9531017980432485,
  0.97580328338864,
  0.9877045036148601,
  0.9938015998845724],
 [0.9820349763865139,
  0.9945958121167238,
  0.9985047687340315,
  0.9996057238410802,
  0.9998986961542847]]

In [14]:
def fwd_richardson(F, X, h, n, deriv_formula=fwd):
    data = np.zeros((n, n))
    step = h
    for i in range(n):
        for j in range(i+1):
            if j == 0:
                data[i][j] = deriv_formula(X, X+step, FX(X), FX(X+step))
                step /= 2
            else:
                data[i][j] = (2) * (data[i][j-1]) - data[i-1][j-1]
    return data
    
    
atc(fwd_richardson(FX, X, h, 3))