In [1]:
fx = sy.cos(sy.pi * x)

In [5]:
X = np.linspace(0, 1, 5)
Y = sy.lambdify(x, fx)(X)
X, Y

(array([0.  , 0.25, 0.5 , 0.75, 1.  ]),
 array([ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17, -7.07106781e-01,
        -1.00000000e+00]))

In [6]:
sy.integrate(fx, (x, 0, 1))

0

In [10]:
from scipy import interpolate as ip
cs = ip.CubicSpline(X, Y, bc_type='natural')

array([[ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17,
        -7.07106781e-01],
       [-7.57359313e-01, -2.00000000e+00, -3.24264069e+00,
        -2.00000000e+00],
       [-4.44089210e-16, -4.97056275e+00, -5.32907052e-15,
         4.97056275e+00],
       [-6.62741700e+00,  6.62741700e+00,  6.62741700e+00,
        -6.62741700e+00]])

In [90]:
coefs = np.flip(cs.c, 0).transpose()
a2l.to_ltx(coefs, arraytype='tabular')

\begin{tabular}
  1.00 & -0.76 & -0.00 & -6.63\\
  0.71 & -2.00 & -4.97 &  6.63\\
  0.00 & -3.24 & -0.00 &  6.63\\
 -0.71 & -2.00 &  4.97 & -6.63
\end{tabular}


In [81]:
eqs = []
for idx, i in enumerate(coefs):
    print(i)
    eq = i[0]
    for power, j in enumerate(i[1:]):
#         display(j, (x - X[idx]) ** (power+1))
        display(eq)
        eq += j * (x - X[idx]) ** (power + 1)
    display(eq)
    eqs.append(eq)

[ 1.00000000e+00 -7.57359313e-01 -4.44089210e-16 -6.62741700e+00]


1.0

1.0 - 0.757359312880715*x

-4.44089209850063e-16*x**2 - 0.757359312880715*x + 1.0

-6.62741699796952*x**3 - 4.44089209850063e-16*x**2 - 0.757359312880715*x + 1.0

[ 0.70710678 -2.         -4.97056275  6.627417  ]


0.7071067811865476

1.20710678118655 - 2.0*x

-2.0*x - 4.97056274847714*(x - 0.25)**2 + 1.20710678118655

-2.0*x + 6.62741699796952*(x - 0.25)**3 - 4.97056274847714*(x - 0.25)**2 + 1.20710678118655

[ 6.12323400e-17 -3.24264069e+00 -5.32907052e-15  6.62741700e+00]


6.123233995736766e-17

1.62132034355964 - 3.24264068711928*x

-3.24264068711928*x - 5.32907051820075e-15*(x - 0.5)**2 + 1.62132034355964

-3.24264068711928*x + 6.62741699796953*(x - 0.5)**3 - 5.32907051820075e-15*(x - 0.5)**2 + 1.62132034355964

[-0.70710678 -2.          4.97056275 -6.627417  ]


-0.7071067811865475

0.792893218813452 - 2.0*x

-2.0*x + 4.97056274847714*(x - 0.75)**2 + 0.792893218813452

-2.0*x - 6.62741699796952*(x - 0.75)**3 + 4.97056274847714*(x - 0.75)**2 + 0.792893218813452

In [82]:
for i, k in enumerate(eqs):
    display(k, (x, X[i], X[i+1]))

-6.62741699796952*x**3 - 4.44089209850063e-16*x**2 - 0.757359312880715*x + 1.0

(x, 0.0, 0.25)

-2.0*x + 6.62741699796952*(x - 0.25)**3 - 4.97056274847714*(x - 0.25)**2 + 1.20710678118655

(x, 0.25, 0.5)

-3.24264068711928*x + 6.62741699796953*(x - 0.5)**3 - 5.32907051820075e-15*(x - 0.5)**2 + 1.62132034355964

(x, 0.5, 0.75)

-2.0*x - 6.62741699796952*(x - 0.75)**3 + 4.97056274847714*(x - 0.75)**2 + 0.792893218813452

(x, 0.75, 1.0)

In [83]:
display(*eqs)

-6.62741699796952*x**3 - 4.44089209850063e-16*x**2 - 0.757359312880715*x + 1.0

-2.0*x + 6.62741699796952*(x - 0.25)**3 - 4.97056274847714*(x - 0.25)**2 + 1.20710678118655

-3.24264068711928*x + 6.62741699796953*(x - 0.5)**3 - 5.32907051820075e-15*(x - 0.5)**2 + 1.62132034355964

-2.0*x - 6.62741699796952*(x - 0.75)**3 + 4.97056274847714*(x - 0.75)**2 + 0.792893218813452

In [91]:
sy.integrate(eqs[0], (x, 0, 0.25)) + \
sy.integrate(eqs[1], (x, 0.25, 0.5)) + \
sy.integrate(eqs[2], (x, 0.5, 0.75)) + \
sy.integrate(eqs[3], (x, 0.75, 0.1))

-0.493792594808639

In [104]:
((eqs[1] - eqs[2]).diff().diff().subs(x, 0.5) - fx.diff().diff().subs(x, 0)).evalf()

9.86960440108937

In [101]:
-math.pi ** 2

-9.869604401089358